version: '3'
services:
  app:
    image: rails-on-argocd
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
