version: '3'
services:
  app: &app
    image: agate/rails-on-argocd:v1
    build:
      context: .
      dockerfile: versions/v1/Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - DB_HOST=db
  appv1:
    <<: *app
    volumes:
      - ./rails:/app
  appv2:
    <<: *app
    image: agate/rails-on-argocd:v2
    build:
      context: .
      dockerfile: versions/v1/Dockerfile
    volumes:
      - ./rails:/app
      - ./versions/v2/app/controllers/main_controller.rb:/app/app/controllers/main_controller.rb
      - ./versions/v2/app/models/user.rb:/app/app/models/user.rb
      - ./versions/v2/config/routes.rb:/app/config/routes.rb
      - ./versions/v2/db/migrate:/app/db/migrate
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
