apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-on-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agate/rails_on_argocd.git
    targetRevision: master
    path: versions/v1/argocd
  destination:
    namespace: rails-on-argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
