kind: Deployment
apiVersion: apps/v1
metadata:
  name: rails-on-argocd-db
  namespace: rails-on-argocd
  labels:
    app.kubernetes.io/name: rails-on-argocd-db
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rails-on-argocd-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rails-on-argocd-db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - name: db
          containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
