kind: Service
apiVersion: v1
metadata:
  name: rails-on-argocd-db
  namespace: rails-on-argocd
  labels:
    app.kubernetes.io/name: rails-on-argocd-db
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  selector:
    app.kubernetes.io/name: rails-on-argocd-db
  ports:
  - name: db
    port: 5432
    targetPort: 5432
