kind: Service
apiVersion: v1
metadata:
  name: rails-on-argocd-app
  namespace: rails-on-argocd
  labels:
    app.kubernetes.io/name: rails-on-argocd-app
spec:
  selector:
    app.kubernetes.io/name: rails-on-argocd-app
  ports:
  - name: app
    port: 3000
    targetPort: 3000
