kind: Deployment
apiVersion: apps/v1
metadata:
  name: rails-on-argocd-app
  namespace: rails-on-argocd
  labels:
    app.kubernetes.io/name: rails-on-argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rails-on-argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rails-on-argocd-app
    spec:
      initContainers:
      - name: migration-checker
        image: agate/rails-on-argocd:master
        command:
        - /bin/sh
        - -c
        - until bundle exec rails db:migrate:status; do echo "waiting for db get migrated"; sleep 2; done
        env:
        - name: DB_HOST
          value: rails-on-argocd-db.rails-on-argocd.svc.cluster.local
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
      containers:
      - name: app
        image: agate/rails-on-argocd:master
        ports:
        - name: app
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: DB_HOST
          value: rails-on-argocd-db.rails-on-argocd.svc.cluster.local
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
