FROM agate/rails-on-argocd:base

COPY version/v2/app/controllers/main_controller.rb /app/app/controllers/main_controller.rb
COPY version/v2/app/models/user.rb /app/app/models/user.rb
COPY version/v2/config/routes.rb /app/config/routes.rb
COPY version/v2/db/migrate /app/db/migrate/
