name: Build & Publish Docker Images

on:
  push:
    branches: ['master']

jobs:
  build_and_publish_docker_images:
    name: Build & Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repo
        uses: actions/checkout@v2
      
      - name: Login To Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker Image - V1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: versions/v1/Dockerfile
          push: true
          tags: agate/rails-on-argocd:v1

      - name: Build & Push Docker Image - V2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: versions/v2/Dockerfile
          push: true
          tags: agate/rails-on-argocd:v2
