name: Build & Publish Docker Images

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker Image - V1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: versions/v1/Dockerfile
          push: true
          tags: agate/rails-on-argocd:v1

      - name: Build & Push Docker Image - V2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: versions/v2/Dockerfile
          push: true
          tags: agate/rails-on-argocd:v2
